# Generated by Django 5.2.6 on 2025-10-06 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='streak_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, null=True, size=None),
        ),
    ]
