# Generated by Django 5.2.7 on 2025-10-10 11:49

import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_streak_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='task',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='task_embedding_index', opclasses=['vector_cosine_ops']),
        ),
    ]
