# Generated by Django 5.2.7 on 2025-10-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleAuth', '0002_googlecredential_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredential',
            name='latest_history_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
